/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lanchonete.forms;


import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lanchonete.atendente.Atendente;
import lanchonete.atendente.DadosAtendente;
import lanchonete.pedido.DadosPedido;
import lanchonete.pedido.Pedido;

/**
 *
 * @author lgdal
 */
public class FormLanchonete4 extends javax.swing.JFrame {
    
        ArrayList<DadosPedido> listaPedidos = new ArrayList<>();
        Atendente atendente = new Atendente();


    /**
     * Creates new form FormLanchonete4
     */
    public FormLanchonete4() {
        initComponents();
        setLocationRelativeTo(null);  
        carregarPedidos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConzinha = new javax.swing.JTable();
        jbCancelarPedido = new javax.swing.JButton();
        jbPedidoEntregue = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbAtualizar = new javax.swing.JButton();
        jbPedidoPronto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jbAtendente1 = new javax.swing.JButton();
        jlAtendente1 = new javax.swing.JLabel();
        jbAtendente2 = new javax.swing.JButton();
        jlAtendente3 = new javax.swing.JLabel();
        jbAtendente3 = new javax.swing.JButton();
        jlAtendente2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COZINHA");

        jPanel1.setBackground(new java.awt.Color(19, 18, 19));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setName("CONZINHA"); // NOI18N

        jTableConzinha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Atendente", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableConzinha);
        if (jTableConzinha.getColumnModel().getColumnCount() > 0) {
            jTableConzinha.getColumnModel().getColumn(1).setPreferredWidth(300);
            jTableConzinha.getColumnModel().getColumn(2).setPreferredWidth(30);
            jTableConzinha.getColumnModel().getColumn(3).setPreferredWidth(10);
        }

        jbCancelarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lanchonete/imagens/icons8-cancelar-34.png"))); // NOI18N
        jbCancelarPedido.setText("CANCELAR");
        jbCancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarPedidoActionPerformed(evt);
            }
        });

        jbPedidoEntregue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lanchonete/imagens/icons8-selecionado-36.png"))); // NOI18N
        jbPedidoEntregue.setText("ENTREGUE");
        jbPedidoEntregue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPedidoEntregueActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        jbAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lanchonete/imagens/icons8-actualizar-40.png"))); // NOI18N
        jbAtualizar.setText("ATUALIZAR LISTA DE PEDIDOS");
        jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarActionPerformed(evt);
            }
        });

        jbPedidoPronto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lanchonete/imagens/icons8-selecionado-36.png"))); // NOI18N
        jbPedidoPronto.setText("PEDIDO PRONTO");
        jbPedidoPronto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPedidoProntoActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 51), java.awt.Color.white));

        jButton1.setText("Atualizar Atendentes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbAtendente1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbAtendente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lanchonete/imagens/icons8-cozinheiro-48.png"))); // NOI18N
        jbAtendente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtendente1ActionPerformed(evt);
            }
        });

        jlAtendente1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlAtendente1.setForeground(new java.awt.Color(255, 255, 51));
        jlAtendente1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlAtendente1.setText("Atendente 1");

        jbAtendente2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbAtendente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lanchonete/imagens/icons8-cozinheiro-48.png"))); // NOI18N
        jbAtendente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtendente2ActionPerformed(evt);
            }
        });

        jlAtendente3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlAtendente3.setForeground(new java.awt.Color(255, 255, 51));
        jlAtendente3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlAtendente3.setText("Atendente 2");

        jbAtendente3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbAtendente3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lanchonete/imagens/icons8-cozinheiro-48.png"))); // NOI18N
        jbAtendente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtendente3ActionPerformed(evt);
            }
        });

        jlAtendente2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlAtendente2.setForeground(new java.awt.Color(255, 255, 51));
        jlAtendente2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlAtendente2.setText("Atendente 3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAtendente3, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(jbAtendente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbAtendente2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jlAtendente1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlAtendente2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlAtendente3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAtendente1)
                    .addComponent(jlAtendente1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAtendente2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAtendente3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAtendente3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlAtendente2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbPedidoPronto, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jbPedidoEntregue, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(273, 273, 273)
                                .addComponent(jLabel2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                .addComponent(jbAtualizar)
                                .addGap(34, 34, 34)
                                .addComponent(jbCancelarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(107, 107, 107)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbPedidoPronto, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(jbPedidoEntregue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbCancelarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbPedidoEntregueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPedidoEntregueActionPerformed
        // TODO add your handling code here:
        String statusPedido = "Entregue";
        int linha = jTableConzinha.getSelectedRow();
        int codigoPedido = (int) jTableConzinha.getValueAt(linha, 0);
        DadosPedido dadosPedido = new DadosPedido();
            try {
                dadosPedido.atualizarPedidoEntregue(statusPedido, codigoPedido);
                JOptionPane.showMessageDialog(this,"Pedido entregue para o cliente!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                carregarPedidos();
            } catch (Exception ex) {
                Logger.getLogger(FormLanchonete4.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Erro ao carregar Pedido entregue", "ERRO", JOptionPane.ERROR_MESSAGE);

            }
    }//GEN-LAST:event_jbPedidoEntregueActionPerformed

    private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed
        // TODO add your handling code here:
        carregarPedidos();
    }//GEN-LAST:event_jbAtualizarActionPerformed

    private void jbCancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarPedidoActionPerformed
        // TODO add your handling code here:
        int linha = jTableConzinha.getSelectedRow();
        int codigoPedido = (int) jTableConzinha.getValueAt(linha, 0);
        DadosPedido dadosPedido = new DadosPedido();
            try {
                dadosPedido.removerPedido(codigoPedido);
                JOptionPane.showMessageDialog(this,"Pedido excluido com sucesso!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                carregarPedidos();


            } catch (Exception ex) {
                Logger.getLogger(FormLanchonete4.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Erro ao ecluir o pedido", "ERRO", JOptionPane.ERROR_MESSAGE);

            }
    }//GEN-LAST:event_jbCancelarPedidoActionPerformed

    private void jbAtendente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtendente1ActionPerformed
        // TODO add your handling code here:
        
        int cod_atendente = 1;
        int linha = jTableConzinha.getSelectedRow();
        int codigoPedido = (int) jTableConzinha.getValueAt(linha, 0);
        DadosPedido dadosPedido = new DadosPedido();
            try {
                dadosPedido.atualizarPedido(cod_atendente, codigoPedido);
                JOptionPane.showMessageDialog(this,"Pedido direcionado para o Atendente 1!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                carregarPedidos();
            } catch (Exception ex) {
                Logger.getLogger(FormLanchonete4.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Erro ao direcionado para o Atendente 1!", "ERRO", JOptionPane.ERROR_MESSAGE);

            }
        
        
        
    }//GEN-LAST:event_jbAtendente1ActionPerformed

    private void jbAtendente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtendente2ActionPerformed
        // TODO add your handling code here:
        
        int cod_atendente = 2;
        int linha = jTableConzinha.getSelectedRow();
        int codigoPedido = (int) jTableConzinha.getValueAt(linha, 0);
        DadosPedido dadosPedido = new DadosPedido();
            try {
                dadosPedido.atualizarPedido(cod_atendente, codigoPedido);
                JOptionPane.showMessageDialog(this,"Pedido direcionado para o Atendente 2!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                carregarPedidos();
            } catch (Exception ex) {
                Logger.getLogger(FormLanchonete4.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Erro ao direcionado para o Atendente 2!", "ERRO", JOptionPane.ERROR_MESSAGE);

            }
        
    }//GEN-LAST:event_jbAtendente2ActionPerformed

    private void jbAtendente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtendente3ActionPerformed
        // TODO add your handling code here:
        
        int atendente = 3;
        int linha = jTableConzinha.getSelectedRow();
        int codigoPedido = (int) jTableConzinha.getValueAt(linha, 0);
        DadosPedido dadosPedido = new DadosPedido();
            try {
                dadosPedido.atualizarPedido(atendente, codigoPedido);
                JOptionPane.showMessageDialog(this,"Pedido direcionado para o Atendente 3!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                carregarPedidos();
            } catch (Exception ex) {
                Logger.getLogger(FormLanchonete4.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Erro ao direcionado para o Atendente 3!", "ERRO", JOptionPane.ERROR_MESSAGE);

            }
        
    }//GEN-LAST:event_jbAtendente3ActionPerformed

    private void jbPedidoProntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPedidoProntoActionPerformed
        // TODO add your handling code here:
        String statusPedido = "Pronto";
        int linha = jTableConzinha.getSelectedRow();
        int codigoPedido = (int) jTableConzinha.getValueAt(linha, 0);
        DadosPedido dadosPedido = new DadosPedido();
            try {
                dadosPedido.atualizarStatus(statusPedido, codigoPedido);
                JOptionPane.showMessageDialog(this,"Pedido pronto para o cliente!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                carregarPedidos();
            } catch (Exception ex) {
                Logger.getLogger(FormLanchonete4.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Erro ao carregar Pedido pronto", "ERRO", JOptionPane.ERROR_MESSAGE);

            }
        

    }//GEN-LAST:event_jbPedidoProntoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            try {
                // TODO add your handling code here:
                DadosAtendente da = new DadosAtendente();
                
                String atendente1 = "Luiz";
                this.jlAtendente1.setText(String.valueOf(atendente1));
                
                String atendente2 = "Pedro";
                this.jlAtendente2.setText(String.valueOf(atendente2));
                
                String atendente3 = "Maria";
                this.jlAtendente3.setText(String.valueOf(atendente3));
                
                
                
                
            } catch (Exception ex) {
                Logger.getLogger(FormLanchonete4.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLanchonete4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLanchonete4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLanchonete4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLanchonete4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLanchonete4().setVisible(true);
            }
        });
    }
    
    private void carregarPedidos(){

        try {
                        
            Pedido filtro = new Pedido();                        
            Pedido pedidos = new Pedido();
            Atendente atendente = new Atendente();
            DadosPedido dadosPedidos = new DadosPedido();
            ArrayList<Pedido> listaPedidos = dadosPedidos.listar(filtro);
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new Object[]{"Código","Descrição","Atendente", "Status"});
            for (Pedido pedido : listaPedidos) {
                modelo.addRow(new Object[]{pedido.getCod(),pedido.getDescricao(),pedido.getCod_atendente(), pedido.getStatus()});
            }
            jTableConzinha.setModel(modelo);
            JOptionPane.showMessageDialog(this, "**LISTA DE PEDIDOS ATUALIZADA**");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConzinha;
    private javax.swing.JButton jbAtendente1;
    private javax.swing.JButton jbAtendente2;
    private javax.swing.JButton jbAtendente3;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbCancelarPedido;
    private javax.swing.JButton jbPedidoEntregue;
    private javax.swing.JButton jbPedidoPronto;
    private javax.swing.JLabel jlAtendente1;
    private javax.swing.JLabel jlAtendente2;
    private javax.swing.JLabel jlAtendente3;
    // End of variables declaration//GEN-END:variables
}
